# Generated by Django 5.0.4 on 2024-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('text', models.TextField(max_length=250, verbose_name='Сообщение')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('create_at', models.TimeField(verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
