# Generated by Django 5.0.4 on 2024-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='create_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.TimeField(default=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='todo',
            name='nick',
            field=models.CharField(default=1, max_length=10, verbose_name='Ник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=999, verbose_name='Запись'),
        ),
    ]
